name: Apocalypse
version: ${project.version}
main: com.justserver.apocalypse.Apocalypse
load: POSTWORLD
api-version: 1.16
commands:
  startdungeon:
    usage: /<command>
  base:
    usage: /base <args>
  additem:
  setup: